### ISSUE TITLE
Bug with tag changes

### ISSUE THREAD

**Issue by geohci** [geohci/edit-types#14]
In `is_change_in_edit_type`, the Tag code block assumes a tag will be found and selects the first one -- e.g., `prev_filtered_ref = prev_parsed_text.filter_tags(matches=lambda node: node.tag == "ref",recursive=False)[0]`. This throws an exception when e.g., the tag is text formatting and not a reference. Probably want to adopt the approach used in the `is_edit_type` function.

**Comment by Amamgbu** [comment]
Alright @geohci. Making fixes now
