### ISSUE TITLE
Support moves in node differ

### ISSUE THREAD

**Issue by geohci** [geohci/edit-types#15]
Counting moves in the node differ in `get_diff_count` will likely look similar to counting changes -- both are nested data structures with `prev` and `curr` keys. Sections with moves can either be added to the `sections_affected` set to make sure they are detected or, **even better**, the `sections_affected` logic can be dropped. It was initially used to order the changes by which section they occurred in for easier explanation, but this doesn't matter for the counting. Instead, can directly loop through the insert/remove/change/move result lists and process. This will be simpler and slightly faster!

**Comment by Amamgbu** [comment]
Alright. I'd take that off the logic and send in a PR shortly
