### ISSUE TITLE
Not detecting changes in text formatting

### ISSUE THREAD

**Issue by geohci** [geohci/edit-types#16]
When text formatting changes -- e.g., `'''Text'''` (bold) to `''Text''` (italic) -- this isn't being detected. I think the issue is with this line: `prev_filtered_text_formatting = re.findall("'{2}.*''", str(prev_filtered_text_formatting[0]))[0]` (and its equivalent for curr) taking I think just the first character of the formatting string by accident but I haven't dug into it. Ideally add a test case to cover this too to verify.

**Comment by Amamgbu** [comment]
I have added test cases and fixed this issue.
