### ISSUE TITLE
Handled nested node changes

### ISSUE THREAD

**Issue by geohci** [geohci/edit-types#5]
Currently the node differ assigns all changes within a node to that node -- e.g., any changes to a Template count as a Template change. This is out of simplicity -- we only have to inspect the top level of nodes then. We instead should assign these changes to the most specific node where it occurred -- e.g., a reference added to a Template should be counted as a reference insert not a Template change. In theory this means a recursive search to find the lowest level where a change happened but, in practice, going to just the second level of nodes probably is sufficient per our conversations.

A more complete set of examples:
* https://wiki-topic.toolforge.org/diff-tagging?lang=en&revid=979988715 should be 1 Template Change. The diff is just adding additional parameters to a single template and even though we can see that one parameter adds an image, that's too complex to detect at this stage.
* https://wiki-topic.toolforge.org/diff-tagging?lang=en&revid=979988715 should be 1 Wikilink Change. The link is in a template but the entire change occurs within the context of a wikilink. If it wasn't a link but was just raw text in the template, then I would count it as a template change but acknowledge that's somewhat arbitrary. Same thing applies for e.g., adding a ref or formatting within a template.
* One exception is the `move` edit type -- if a Template is moved, it should just be counted as 1 Template Move regardless of what is contained within the template.
* I'm less certain about how to count insert/remove edit types for nested nodes. Right now I think it should be like a change though -- i.e. a new template (such as this, though it has some other text etc. added on top of the infobox template: https://wiki-topic.toolforge.org/diff-tagging?lang=en&revid=615322611) should also trigger Inserts for all the nested links, references, etc.

**Comment by Amamgbu** [comment]
Update:
@geohci and I discussed and came to the conclusion that:

If a reference/link/etc. is added to a template, this still triggers a template change. More generally, nested changes still trigger a single high-level change too

**Comment by geohci** [comment]
Just quick summary of our discussion:
* I'll address this Issue with the tree-differ now that I'm aware of the general `filter` functionality in mwparserfromhell and our initial examination
* This exploration of working with nested nodes in Templates etc. in the node-differ will be repurposed in the future for detecting more fine-grained changes in certain types of nodes -- e.g., not just whether a Template was changed but how many parameters (and maybe which ones). Same potential sub-analyses could be done for e.g., tables (how many cells were edited), images (caption changed? parameters changed?) but these will be logged as a separate issue.
