### ISSUE TITLE
Expand sentence break punctuation

### ISSUE THREAD

**Issue by geohci** [geohci/edit-types#51]
Build a list of punctuation that marks the end of sentences in constants.py and use that in the sentence tokenizing. This will make it easier to add new punctuation as we explore CJK etc.

**Comment by geohci** [comment]
Reminder that when we fix this, we'll have to update the change CJK punctuation tests if they switch sentence ending punctuation to non-sentence-ending punctuation (e.g., equivalent of period -> comma)

**Comment by Amamgbu** [comment]
Okay @geohci.

 I would do that.

**Comment by geohci** [comment]
Probably more but we have CJK and Bengali sentence breaks so that's a good start
