### ISSUE TITLE
Simplify regexes

### ISSUE THREAD

**Issue by geohci** [geohci/edit-types#58]
Right now the sentence-break regex has two parts:
* The first part is any length set of end-of-sentence punctuation (e.g., exclamation marks). This part is simple and easy to update with new punctuation!
* The second part does a complicated check to ensure no ellipses (three consecutive periods) and no decimal numbers (`#.#`) are included as sentence-breaks. These two checks are actually very similar and probably can be merged as including periods only if they aren't preceded by a period of number and followed by a period or number -- i.e. (no period or number)(single period)(no period or number). This isn't exactly the same as what is there because this approach would also capture mixed sets like #.. or ..# but both of those seem rare/ambiguous so probably not an issue. Updating it will make it easier to decipher and update in case we encounter other characters we want to include in this.

Separately, it would be good to have more documentation (comments) for the `NON_ENGLISH_UNICODE` and `ENGLISH_UNICODE` variables so it's clearer what Unicode ranges are included in them.

**Comment by Amamgbu** [comment]
Alright @geohci

**Comment by geohci** [comment]
We attempted to clean it up but didn't find a good solution that still covered all the use-cases. Closing as a result.
