### ISSUE TITLE
Capture all list types as single List node

### ISSUE THREAD

**Issue by geohci** [geohci/edit-types#7]
Tree differ will continue to pass the generic Tag nodes. The node differ currently distinguishes between `Table`, `Reference`, and `Text Formatting`. Add to that a `List` result which is a match against the following type of tags: `li`, `dd`, and `dt` (see: https://github.com/earwig/mwparserfromhell/blob/8cd0bdb322b0de1a8e41097eb674ac8671c99bbd/src/mwparserfromhell/definitions.py#L108). They are slightlly different in how they are displayed on Wikipedia but all result in a list and are relatively uncommon so it feels reasonable to just go with the generic List type.

**Comment by Amamgbu** [comment]
Alright. List type support has been implemented.
